### PR TITLE
Add Buster ahead of release

### PR DESCRIPTION
**Pull request by filippog**
Useful to test Buster within Docker containers.

### CODE REVIEW

**Comment by filippog** [comment]
There's likely some trimming in packages installed to do as well, either here or in a followup PR. What do you think?

```diff
--- minideb:stable
+++ minideb:buster
@@ -11,8 +11,9 @@
 debianutils
 diffutils
 dpkg
+fdisk
 findutils
-gcc-6-base:amd64
+gcc-8-base:amd64
 gpgv
 grep
 gzip
@@ -32,18 +33,26 @@
 libdb5.3:amd64
 libdebconfclient0:amd64
 libfdisk1:amd64
+libffi6:amd64
 libgcc1:amd64
 libgcrypt20:amd64
+libgmp10:amd64
+libgnutls30:amd64
 libgpg-error0:amd64
+libhogweed4:amd64
+libidn2-0:amd64
 liblz4-1:amd64
 liblzma5:amd64
 libmount1:amd64
-libncursesw5:amd64
+libncursesw6:amd64
+libnettle6:amd64
+libp11-kit0:amd64
 libpam-modules:amd64
 libpam-modules-bin
 libpam-runtime
 libpam0g:amd64
 libpcre3:amd64
+libseccomp2:amd64
 libselinux1:amd64
 libsemanage-common
 libsemanage1:amd64
@@ -51,20 +60,20 @@
 libsmartcols1:amd64
 libstdc++6:amd64
 libsystemd0:amd64
-libtinfo5:amd64
+libtasn1-6:amd64
+libtinfo6:amd64
 libudev1:amd64
-libustr-1.0-1:amd64
+libunistring2:amd64
 libuuid1:amd64
+libzstd1:amd64
 login
 lsb-base
 mawk
 mount
-multiarch-support
 ncurses-base
 passwd
 perl-base
 sed
-sensible-utils
 startpar
 sysv-rc
 sysvinit-utils
```

**Comment by james-w** [comment]
Sorry that I missed this, and thanks for looking at it. I hope that you were able to do the testing that you needed.

The tests are failing as they cannot install `mysql-server`. This is a regression test as that package
triggered a terminfo problem. It looks like that package has transitioned to `default-mysql-server`, and
that was available in stretch, but not jessie, so we might have to make the test conditional somehow.

Most of those packages sound like they would be required. `fdisk` can likely be dropped, and we would
have to check the libraries.

**Comment by james-w** [comment]
Thanks for this. I took the liberty of taking it over and landing it as 2c4b4f0f140f6b5ff4b09def2525ecb64978ddb8.

Thanks,

James

**Comment by filippog** [comment]
> Thanks for this. I took the liberty of taking it over and landing it as [2c4b4f0](https://github.com/bitnami/minideb/commit/2c4b4f0f140f6b5ff4b09def2525ecb64978ddb8).

Fantastic, thank you! This is great.

**Pull request closed without merging**
